## Dot Product - Associative and Distributive Properties

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Distributive Property

The dot product **is** distributive, like in scalar algebra

#### a(b+c) = ab+ac

#### a<sup>T</sup>(b+c)= a<sup>T</sup>b + a<sup>T</sup>c



In [3]:
## Distributive Property

# create random vectors
n = 10
a = np.random.randn(n)
b = np.random.randn(n)
c = np.random.randn(n)

# demonstrating the distributive property of the dot products of vector a with
# b, and c
res1 = np.dot( a, (b+c) )
res2 = np.dot(a,b) + np.dot(a,c)

# show the comparison
print([ res1, res2 ])

[np.float64(3.8247354369506814), np.float64(3.824735436950681)]


### Associative Property

The dot product **is not** associative, although it is in scalar algebra

#### a(b*c) = (a*b)c

#### a<sup>T</sup>(b<sup>T</sup>c) $\neq$ (a<sup>T</sup>b)<sup>T</sup>c

In [5]:
## Associative Property

# create random vectors
n = 5
a = np.random.randn(n)
b = np.random.randn(n)
c = np.random.randn(n)

# demonstrating that the dot products do not hold to the associative property
res1 = np.dot( a, np.dot(b,c) )
res2 = np.dot( np.dot(a,b) , c )

# show the comparison
print(res1)
print(res2)

### special cases where associative property works

# 1) one vector is the zeros vector

v1 = [1, 2, 3]
v2 = [4, 5, 6]
v3 = [0, 0, 0]

res3 = np.dot( v1, np.dot(v2,v3) )
res4 = np.dot( np.dot(v1,v2) , v3 )

print(res3)
print(res4)

# 2) a==b==c

v4 = [1, 2, 3]
v5 = [1, 2, 3]
v6 = [1, 2, 3]

res5 = np.dot( v4, np.dot(v5,v6) )
res6 = np.dot( np.dot(v4,v5) , v6 )

print(res5)
print(res6)


[-0.18155025  0.02094523  0.17433899  0.19197423 -1.10254249]
[-0.24648454 -0.88339867 -0.79393462  0.02782235 -0.00476457]
[0 0 0]
[0 0 0]
[14 28 42]
[14 28 42]
