## Outer Product

In [1]:
import numpy as np

#### Outer oroduct notation:
$$\mathbf{u} \otimes \mathbf{v} = \mathbf{u}\mathbf{v}^T$$

#### Can be calculated using different size vectors


In [8]:
# generate vectors
v1 = np.array([1, 2, 3])
v2 = np.array([-1, 0, 1])

# outer product
op1 = np.outer(v1, v2)

# conceptualize
op2 = np.zeros((len(v1), len(v2)))
for i in range(0, len(v1)):
    for j in range(0, len(v2)):
        op2[i, j] = v1[i] * v2[j]

# show results
print(op1)
print(op2)

[[-1  0  1]
 [-2  0  2]
 [-3  0  3]]
[[-1.  0.  1.]
 [-2.  0.  2.]
 [-3.  0.  3.]]


##### np.outer function is the preferred method when calculating outer product