In [1]:
# ======================================================================
# SECTION: MATRIX RANK AND LINEAR DEPENDENCY
# COMPLEXITY: O(min(m^2n, mn^2)) - SVD-based rank computation.
# DATA SHAPE: Input (m x n), Rank is a scalar (r <= min(m, n)).
# MATH: rank(A) = dim(col(A))
# TOOLS: np.linalg.matrix_rank(), np.random.randn(), .copy()
# ======================================================================

import numpy as np

# set global print options
np.set_printoptions(suppress=True, precision=3)

### Matrix Rank
This experiment explores the computational method of determining the rank of a matrix using np.linalg.matrix_rank(). The rank represents the number of linearly independent rows or columns in a matrix and defines the dimensionality of the subspace spanned by those vectors.
#### Key Concepts:
* Full Rank: When the rank equals the smallest dimension of the matrix ($min(m, n)$).
* Rank Deficiency: Occurs when vectors are linearly dependent (e.g., one column is a multiple or sum of others), reducing the information density of the matrix.
* Numerical Stability: numpy uses Singular Value Decomposition (SVD) to estimate rank, which is more robust against floating-point errors than Gaussian elimination.

In [20]:
# Create random matrix (m x n)
matrix_rows = 5
matrix_cols = 3
matrix = np.random.randn(matrix_rows, matrix_cols)

# Compute matrix rank
rank = np.linalg.matrix_rank(matrix)
print(f"Matrix:\n{matrix}\n")
print(f"Shape: {matrix.shape}")
print(f"Rank of the matrix: {rank}\n")

# REDUCED RANK EXPERIMENT
# Set the last column to the same value as the penultimate column
# This creates a linear dependency: col[n] = col[n-1]
reduced_rank_matrix = matrix.copy() # Using .copy() to preserve original for comparison
reduced_rank_matrix[:, -1] = matrix[:, -2]

print(f"Reduced matrix:\n{reduced_rank_matrix}\n")
reduced_rank = np.linalg.matrix_rank(reduced_rank_matrix)
print(f"Shape: {reduced_rank_matrix.shape}")
print(f"Rank of the reduced matrix: {reduced_rank}")

# Verification for ML readiness
assert reduced_rank < rank, "Rank did not decrease as expected."

Matrix:
[[ 0.041 -1.162  0.951]
 [ 0.848  1.471  0.223]
 [-1.377 -0.197 -1.396]
 [-0.075 -0.586 -0.257]
 [-0.85   0.373  0.656]]

Shape: (5, 3)
Rank of the matrix: 3

Reduced matrix:
[[ 0.041 -1.162 -1.162]
 [ 0.848  1.471  1.471]
 [-1.377 -0.197 -0.197]
 [-0.075 -0.586 -0.586]
 [-0.85   0.373  0.373]]

Shape: (5, 3)
Rank of the reduced matrix: 2
