In [1]:
# ======================================================================
# SECTION: FROBENIUS DOT PRODUCT AND MATRIX NORM
# COMPLEXITY: O(m * n) for Vectorized; O(m^2 * n) for Trace method.
# DATA SHAPE: A(m, n), B(m, n) -> Result(scalar).
# MATH: <A,B>F = sum(A{ij} * B_{ij}) = Tr(A^T B).
# TOOLS: np.reshape(), np.trace(), np.linalg.norm(), np.allclose()
# ======================================================================

import numpy as np

# set global print options
np.set_printoptions(suppress=True, precision=3)

### Frobenius Dot Product
The Frobenius Dot Product is the matrix equivalent of the standard vector dot product.
It allows us to compute a single scalar value that represents the relationship between two matrices of the same dimensions.
This is a foundational concept for measuring "distance" or "similarity" between matrices in Machine Learning and AI.

#### 🛠️ Methods of Calculation
##### 1. The Vectorized Method (Geometric)

The most intuitive way to think about this is to "unroll" (flatten) both matrices into long vectors and then perform a standard dot product.
In NumPy, this is efficiently handled as an element-wise multiplication followed by a sum.
* Formula: $\langle A,B \rangle_F = \sum_{i,j} A_{ij} B_{ij}$
* Best for: Computational efficiency ($O(mn)$).

##### 2. The Trace Method (Algebraic)

A more sophisticated algebraic definition uses the Trace of a matrix product.
This method is mathematically elegant and often used in proofs, though it is computationally heavier.
* Formula: $\langle A,B \rangle_F = \text{Tr}(A^T B)$
* Best for: Theoretical derivations and matrix calculus.

#### 📏 The Frobenius Norm
Just as the norm of a vector is the square root of its dot product with itself, the Frobenius Norm ($||A||_F$) measures the "size" or "magnitude" of a matrix.
* Relationship: $||A||_F = \sqrt{\langle A,A \rangle_F}$
* Verification: In this notebook, we verify that np.linalg.norm(A) is equivalent to $\sqrt{\text{Tr}(A^T A)}$.

In [4]:
# create matrices
m_dim = 6
n_dim = 4

mat_A = np.random.randn(m_dim,n_dim)
mat_B = np.random.randn(m_dim,n_dim)

assert mat_B.shape == mat_A.shape
print(f"Matrix A: \n{mat_A}\n")
print(f"Matrix B: \n{mat_B}\n")

# Method 1: Vectorized
A_vec = np.reshape(mat_A, m_dim*n_dim, order='F')
B_vec = np.reshape(mat_B, m_dim*n_dim, order='F')
frob_dp = np.sum(mat_A * mat_B)

# Method 2: Trace
frob_dp_2 = np.trace(mat_A.T @ mat_B)

assert np.allclose(frob_dp, frob_dp_2)
print(f"Frobenius Dot Product: \n{frob_dp}\n")

# matrix norm
Anorm_1 = np.linalg.norm(mat_A)
Anorm_2 = np.sqrt( np.trace(mat_A.T @ mat_A))

assert np.allclose(Anorm_1, Anorm_2)
print(f"Matrix Norm: \n{Anorm_1}\n")

Matrix A: 
[[ 1.89   0.505  1.12  -0.65 ]
 [-0.622  0.775  0.171  0.364]
 [-1.445  0.243  1.421 -0.717]
 [-1.218 -1.046  0.739  1.004]
 [-1.155 -1.237 -1.986 -0.343]
 [ 0.164  1.196 -0.397 -0.8  ]]

Matrix B: 
[[-0.684  0.127  1.081  0.562]
 [ 0.829  0.204 -2.085 -0.143]
 [ 0.872 -1.689  1.13   1.274]
 [-0.108  0.799  1.011 -0.095]
 [-0.831 -1.152  2.059 -1.651]
 [-1.272  0.568 -0.856 -0.385]]

Frobenius Dot Product: 
-2.199708902229161

Matrix Norm: 
4.964443639826632

