In [2]:
# ======================================================================
# SECTION: HADAMARD PRODUCT (ELEMENT-WISE MULTIPLICATION)
# COMPLEXITY: O(m * n) - Single pass through all elements.
# DATA SHAPE: A.shape == B.shape (m x n) -> Output (m x n)
# MATH: C = A ⊙ B (where C_ij = A_ij * B_ij)
# TOOLS: np.multiply(), * operator, np.allclose()
# ======================================================================

import numpy as np

# set global print options
np.set_printoptions(suppress=True, precision=3)

### Hadamard (Element-wise) Multiplication

#### 1. Definition
Unlike standard matrix multiplication (dot product), the Hadamard Product ($A \odot B$) multiplies corresponding elements.$$C_{i,j} = A_{i,j} \times B_{i,j}$$

#### 2. Constraints & Properties
* Dimensions: Both matrices MUST have the same shape $(m \times n)$.
* Commutativity: $A \odot B = B \odot A$ (Unlike the dot product $AB \neq BA$).
* Implementation: In NumPy, both np.multiply(A, B) and the * operator perform Hadamard multiplication.
* ML Context: This is the operation used for applying Dropout layers (multiplying by a mask of zeros and ones) or scaling feature vectors.

In [4]:
# create matrices
m = 9
n = 12

A = np.random.randn(m,n)
B = np.random.randn(m,n)

# methods for element-wise multiplication
C1 = np.multiply(A, B)
C2 = A * B

print(f"Matrices are equal? {np.allclose( C1, C2)}")

Matrices are equal? True


### Code Challenge: Standard and Hadamard Multiplication for Symmetric Matrices

In [4]:
# ======================================================================
# SECTION: DOT PRODUCT VS. HADAMARD (GENERAL VS. DIAGONAL)
# COMPLEXITY: O(n^3) - Standard Product (np.matmul) vs. O(n^2) Hadamard.
# DATA SHAPE: F (n x n) and D (n x n) -> Output (n x n)
# MATH: F @ F != F * F (General) | D @ D == D * D (Diagonal Only)
# TOOLS: np.random.seed(), np.diag(), np.matmul(), *, np.allclose()
# ======================================================================

# create functions for matrix comparison and product creation
def assert_square_matrix(matrix, size):
    expected_shape = (size, size)
    assert matrix.shape == expected_shape


def standard_product(matrix):
    return np.matmul(matrix, matrix)


def hadamard_product(matrix):
    return matrix * matrix


def create_matrices(seed, size, low, high):
    np.random.seed(seed)
    full_matrix = np.random.randint(low, high, size=(size, size))
    diagonal_matrix = np.diag(np.random.randint(low, high, size=size))
    return full_matrix, diagonal_matrix


# create two matrices (4x4 - full and diagonal)
m = 4  # matrix dimensions
seed_value = 24
value_low = -5
value_high = 6

F, D = create_matrices(seed=seed_value, size=m, low=value_low, high=value_high)

# confirm that the matrices are square
assert_square_matrix(F, m)
assert_square_matrix(D, m)

# multiply each matrix by itself (standard and hadamard multiplications)
S1 = standard_product(F)
H1 = hadamard_product(F)

S2 = standard_product(D)
H2 = hadamard_product(D)

# print the results
print("General matrix comparison:")
print(f"  Equal? {np.allclose(S1, H1)}")
print(f"  Standard product:\n{S1}")
print(f"  Hadamard product:\n{H1}")

print("\nDiagonal matrix comparison:")
print(f"  Equal? {np.allclose(S2, H2)}")
print(f"  Standard product:\n{S2}")
print(f"  Hadamard product:\n{H2}")


General matrix comparison:
  Equal? False
  Standard product:
[[ 18  28  46   0]
 [ 34  30  44   7]
 [ 18  12  14  12]
 [  0 -18 -22  -5]]
  Hadamard product:
[[ 9  4 25  4]
 [16 16 16  1]
 [ 1  4  9  4]
 [ 4  4 16  9]]

Diagonal matrix comparison:
  Equal? True
  Standard product:
[[ 4  0  0  0]
 [ 0  4  0  0]
 [ 0  0 16  0]
 [ 0  0  0  4]]
  Hadamard product:
[[ 4  0  0  0]
 [ 0  4  0  0]
 [ 0  0 16  0]
 [ 0  0  0  4]]
