In [1]:
import numpy as np

# set global print options
np.set_printoptions(suppress=True, precision=3)

### 1. Row-wise Broadcasting (The Default)
When a 1D vector's length matches the number of columns in a matrix, NumPy automatically "stretches" that vector down to every row.

Matrix A: (5, 4)

Vector c: (4,)

Result: (5, 4) + (4,) → Success

#### 2. Column-wise Broadcasting (The Reshape)
To add a vector to every column, the vector must match the number of rows and must be explicitly 2D.

Matrix A: (5, 4)

Vector f: (5, 1)

Result: (5, 4) + (5, 1) → Success

In [24]:
# create a matrix
A = np.reshape(np.arange(1, 21), (5, 4), 'F') # F = by column, C = by row (default)

# create vectors
c = [12, 25, 100, 200]
f = [24, 50, 200, 400, 800]

print(f"Original Matrix: \n{A}\n")
print(f"Row Vector: \n{c}\n")
print(f"Column Vector: \n{np.reshape(f, (len(f),1))}\n")

# broadcast on rows
print(f"Broadcast on Rows: \n{A+c}\n")
print(f"Broadcast on Columns: \n{A+np.reshape(f, (len(f), 1))}\n")

Original Matrix: 
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]

Row Vector: 
[12, 25, 100, 200]

Column Vector: 
[[ 24]
 [ 50]
 [200]
 [400]
 [800]]

Broadcast on Rows: 
[[ 13  31 111 216]
 [ 14  32 112 217]
 [ 15  33 113 218]
 [ 16  34 114 219]
 [ 17  35 115 220]]

Broadcast on Columns: 
[[ 25  30  35  40]
 [ 52  57  62  67]
 [203 208 213 218]
 [404 409 414 419]
 [805 810 815 820]]

