In [1]:
import numpy as np

### Diagonal and Trace

#### 1. The np.diag() Dual-Functionality Matrix to Vector:
Passing a 2D array into np.diag() extracts the main diagonal elements into a 1D vector.
* Vector to Matrix: Passing a 1D vector into np.diag() creates a square diagonal matrix with those elements on the main diagonal and zeros elsewhere.
* Logic: This "toggle" behavior makes it a primary tool for both matrix regularization and element extraction.

#### 2. The Trace Operator (tr) Definition:
The sum of all elements on the main diagonal of a square matrix.
* Implementation:Direct: np.trace(M) is the optimized NumPy approach.
* Manual: sum(np.diag(M)) provides a programmatic verification of the definition.
* Properties: The trace is a linear operator, meaning $tr(A + B) = tr(A) + tr(B)$.
#### 3. Numerical Verification Consistency Check:
Both the direct trace method and the summed diagonal method must yield identical scalar results.
* Randomization: Using np.random.randn scaled by a factor (e.g., 5) helps test the robustness of the trace logic against varied floating-point values.

In [10]:
# create a matrix
M = np.round(5*np.random.randn(3,3) )

# extract the diagonals
d = np.diag(M)
''' if the np.diag input is a matrix, the output will be a vector.
the reverse is also true. '''
D = np.diag(d)

print("\n" + "="*30, f"\nDiagonal Output (Vector):\n{d}")
print("\n" + "="*30, f"\nDiagonal Output (Matrix):\n{D}")

# trace as a sum of diagonal elements
tr = np.trace(M)
# alternative method
tr2 = sum( np.diag(M) )

print("\n" + "="*30, f"\nTrace of Diagonal Output:\n{tr,tr2}\n")
print(f"*Note: Both methods produce the same result!\n" + "="*30)


Diagonal Output (Vector):
[ -2. -12.   4.]

Diagonal Output (Matrix):
[[ -2.   0.   0.]
 [  0. -12.   0.]
 [  0.   0.   4.]]

Trace of Diagonal Output:
(np.float64(-10.0), np.float64(-10.0))

*Note: Both methods produce the same result!
