In [18]:
# ======================================================================
# SECTION: DIAGONAL MATRIX MULTIPLICATION (SCALING)
# COMPLEXITY: O(n^2) - Much faster than O(n^3) since most elements are 0.
# DATA SHAPE: A(n, n) and D(n, n) -> Result(n, n).
# MATH: Post-D = Column Scaling | Pre-D = Row Scaling.
# TOOLS: np.diag(), @ operator, np.allclose()
# ======================================================================

import numpy as np

### Diagonal Matrix Multiplication
Multiplying by a diagonal matrix $D$ is computationally cheaper and conceptually simpler than standard matrix multiplication. It acts as a weighting mechanism.
* Post-Multiplication ($A \times D$): Each column $j$ of $A$ is scaled by the corresponding diagonal element $D_{j,j}$.
* Pre-Multiplication ($D \times A$): Each row $i$ of $A$ is scaled by the corresponding diagonal element $D_{i,i}$.

#### 🛠️ NumPy Implementation
While @ works perfectly, in high-performance computing, you can often achieve this with element-wise broadcasting (e.g., A * np.diag(D)) which is even faster.

In [17]:
# create matrices
n = 4

A = np.random.randint(1,10,(n,n))
D = np.diag([1,2,3,4])

print(f"Matrix A: \n{A}\n")
print(f"Diagonal Matrix D: \n{D}\n")

# post-multiply D = weighted columns
print(f"Result is Weighted Columns: \n{A@D}\n")
# broadcasting is faster than @ with same results
print(f"Result is Weighted Columns (Method 2): \n{A * np.diag(D)}\n")
print(f"Results are the same? {np.allclose(A@D, A * np.diag(D))}\n")

# pre=multiply D = weighted rows
print(f"Result is Weighted Rows: \n{D@A}")

Matrix A: 
[[3 8 2 6]
 [4 5 5 7]
 [3 9 8 3]
 [2 4 2 8]]

Diagonal Matrix D: 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Result is Weighted Columns: 
[[ 3 16  6 24]
 [ 4 10 15 28]
 [ 3 18 24 12]
 [ 2  8  6 32]]

Result is Weighted Columns (Method 2): 
[[ 3 16  6 24]
 [ 4 10 15 28]
 [ 3 18 24 12]
 [ 2  8  6 32]]

Results are the same? True

Result is Weighted Rows: 
[[ 3  8  2  6]
 [ 8 10 10 14]
 [ 9 27 24  9]
 [ 8 16  8 32]]
