In [31]:
# ======================================================================
# SECTION: MATRIX-VECTOR MULTIPLICATION IDENTITIES
# COMPLEXITY: O(n^2) - Matrix(n,n) * Vector(n,1) requires n^2 operations.
# DATA SHAPE: A(5,5) @ w(5,) -> Result(5,). NumPy treats (5,) as flex-shape.
# MATH: (Aw)^T = w^T A^T | If S=S^T, then Sw = (w^T S)^T.
# TOOLS: np.allclose(), dict-based iteration for clean logging.
# ======================================================================

import numpy as np

# Set global print options for clean output
np.set_printoptions(suppress=True, precision=3)

### Matrix-Vector Multiplication
The key takeaway here is that for any matrix $A$ and vector $w$:
* Standard Identity: $(Aw)^T = w^T A^T$. In NumPy, A @ w is the column-vector result, and w @ A.T is its row-vector equivalent.
* Symmetric Identity: If $S = S^T$, then $Sw$ is essentially the same operation regardless of which side $w$ is on (though its "shape" as a row or column depends on the order).

In [30]:
# 1. SETUP
n = 5
A = np.random.randint(-10, 11, (n, n))
# Use @ for matrix multiplication to ensure S is truly symmetric
S = np.round((A.T @ A) / n**2)
w = np.array([-2, -1, 0, 1, 2])

print(f"Non-symmetric Matrix A:\n{A}\n")
print(f"Symmetric Matrix S:\n{S}\n")
print(f"Vector w: {w}\n")

# 2. SYMMETRIC EVALUATION
# Since S = S.T, all these variations are mathematically identical
sym_ops = {
    "S @ w": S @ w,
    "S.T @ w": S.T @ w,
    "w @ S": w @ S,
    "w.T @ S.T": w.T @ S.T,
    "w.T @ S": w.T @ S
}

print("--- Symmetric Results ---")
for label, result in sym_ops.items():
    print(f"{label}: {result}")

# Formal Check
all_sym_equal = all(np.allclose(list(sym_ops.values())[0], r) for r in sym_ops.values())
print(f"\nAll Symmetric variations equal? {all_sym_equal}\n")

# 3. NON-SYMMETRIC EVALUATION (Grouped by Identity)
# Group A: (Aw)^T = w^T A^T
group_a = {"A @ w": A @ w, "w.T @ A.T": w.T @ A.T}

# Group B: (A^T w)^T = w^T A
group_b = {"A.T @ w": A.T @ w, "w @ A": w @ A, "w.T @ A": w.T @ A}

print("--- Non-Symmetric Group A (Aw) ---")
for label, result in group_a.items():
    print(f"{label}: {result}")

print("\n--- Non-Symmetric Group B (A^T w) ---")
for label, result in group_b.items():
    print(f"{label}: {result}")

Non-symmetric Matrix A:
[[-8 -7 -3  2 -5]
 [ 7  6  1 -7 -4]
 [-1  2 -2 -3  4]
 [ 7 -7 -1  2 -4]
 [-6  8  9  2 -6]]

Symmetric Matrix S:
[[ 8. -0. -1. -2.  1.]
 [-0.  8.  4. -2. -0.]
 [-1.  4.  4.  0. -2.]
 [-2. -2.  0.  3. -1.]
 [ 1. -0. -2. -1.  4.]]

Vector w: [-2 -1  0  1  2]

--- Symmetric Results ---
S @ w: [-16. -10.  -6.   7.   5.]
S.T @ w: [-16. -10.  -6.   7.   5.]
w @ S: [-16. -10.  -6.   7.   5.]
w.T @ S.T: [-16. -10.  -6.   7.   5.]
w.T @ S: [-16. -10.  -6.   7.   5.]

All Symmetric variations equal? True

--- Non-Symmetric Group A (Aw) ---
A @ w: [ 15 -35   5 -13  -6]
w.T @ A.T: [ 15 -35   5 -13  -6]

--- Non-Symmetric Group B (A^T w) ---
A.T @ w: [ 4 17 22  9 -2]
w @ A: [ 4 17 22  9 -2]
w.T @ A: [ 4 17 22  9 -2]
