In [1]:
import numpy as np

### Matrix Addition and Subtraction

#### 1. Matrix Addition & Subtraction

Matrix addition and subtraction are element-wise operations. They are only defined for matrices of identical dimensions ($m \times n$).

Implementation Methods:

Operator Overloading: Using A + B or A - B.

NumPy Functions: Using np.add(A, B) or np.subtract(A, B).

In most high-performance systems, these methods are functionally equivalent, but using explicit NumPy functions can sometimes improve readability in complex nested expressions.

#### 2. Shifting a Matrix (Regularization)

Shifting a matrix involves adding a scaled version of the Identity Matrix ($I$) to a square matrix ($C$).

The Formula:

$$C_s = C + \lambda I$$

Where:

$C$ is the original square matrix.

$\lambda$ (Lambda) is a scalar value (the "shift" amount).

$I$ is the Identity matrix of the same size as $C$.

Engineering Significance:

As noted in the code, this operation only affects the diagonal of the matrix. In engineering and AI (specifically in "Ridge Regression" or "Tikhonov Regularization"), this is used to:

Improve Numerical Stability: Prevents division-by-zero or singular matrix errors.

Ensure Invertibility: Adding a small value to the diagonal can make a matrix invertible if it was previously "singular" (non-invertible).

#### 3. Engineering Reflection: Integrity of Operations

Dimensional Integrity: Before execution, we must ensure $Shape(A) = Shape(B)$.

Precision Management: Using np.set_printoptions(suppress=True, precision=3) is a best practice for readability, preventing "scientific notation clutter" when dealing with very small floating-point values.

In [26]:
# set global print options
np.set_printoptions(suppress=True, precision=3)

# create matrices
A = np.random.randn(4,3)
B = np.random.randn(4,3)

print("\n" + "="*32)
print(f"Matrix Addition: A+B = \n{A+B}\n")
print(f"Matrix Addition using the 'np.add' function: A+B = \n{np.add(A,B)}\n")
print("="*32 + "\n")
print(f"Matrix Subtraction: A-B = \n{A-B}\n")
print(f"Matrix Subtraction using the 'np.subtract' function: A-B = \n{np.subtract(A,B)}\n")

# shift a matrix
l = .4 # Lambda (scalar)
N = 4 # square matrix size
C = np.random.randn(N,N)

Cs = C + l*np.eye(N)
print("\n" + "="*32)
print(f"Original Matrix C = \n{C}\n")
print(f"Shifted Matrix C = \n{Cs}")
print(f"*Note: The Shifted Matrix only affects the diagonal of C.")
print("="*32 + "\n")


Matrix Addition: A+B = 
[[ 2.184  0.29   0.635]
 [ 0.403 -0.438 -1.996]
 [-0.538  0.586  0.194]
 [ 0.135 -2.271  0.215]]

Matrix Addition using the 'np.add' function: A+B = 
[[ 2.184  0.29   0.635]
 [ 0.403 -0.438 -1.996]
 [-0.538  0.586  0.194]
 [ 0.135 -2.271  0.215]]


Matrix Subtraction: A-B = 
[[-0.204  0.374 -1.611]
 [-0.812 -2.845 -0.162]
 [-2.067  0.21   0.756]
 [-1.246 -1.613  0.905]]

Matrix Subtraction using the 'np.subtract' function: A-B = 
[[-0.204  0.374 -1.611]
 [-0.812 -2.845 -0.162]
 [-2.067  0.21   0.756]
 [-1.246 -1.613  0.905]]


Original Matrix C = 
[[-0.341 -0.975  1.792 -0.299]
 [-1.115  0.174  0.328  1.565]
 [-0.675 -0.128  0.208 -0.35 ]
 [-0.723 -0.658 -0.585 -0.799]]

Shifted Matrix C = 
[[ 0.059 -0.975  1.792 -0.299]
 [-1.115  0.574  0.328  1.565]
 [-0.675 -0.128  0.608 -0.35 ]
 [-0.723 -0.658 -0.585 -0.399]]
*Note: The Shifted Matrix only affects the diagonal of C.

