In [4]:
# ======================================================================
# SECTION: TRANSPOSE ORDER OF OPERATIONS (REVERSAL RULE)
# COMPLEXITY: O(k * n^3) - Multi-stage multiplication for k matrices.
# DATA SHAPE: (L@I@V@E).T == E.T @ V.T @ I.T @ L.T
# MATH: (ABCD)^T = D^T C^T B^T A^T
# TOOLS: np.matrix.transpose(), .T attribute, np.allclose()
# ======================================================================

import numpy as np

# set global print options
np.set_printoptions(suppress=True,precision=3)

### Order of Operations of Matrices
The transpose of a product of matrices is the product of their transposes in reverse order.
* The Rule (mnemonic - LIVE EVIL): $(LIVE)^T = E^T \cdot V^T \cdot I^T \cdot L^T$

Why? Matrix dimensions must stay aligned.

Since $A(m \times n) \times B(n \times p)$ results in $(m \times p)$, the transpose must be $(p \times m)$.

Flipping the order is the only way to keep the inner dimensions matching after the individual matrices are transposed.

In [6]:
# create matrices
n = 3
L = np.random.randn(n,n)
I = np.random.randn(n,n)
V = np.random.randn(n,n)
E = np.random.randn(n,n)

# forward multiplication then transpose
F = np.matrix.transpose(L@I@V@E)

# multiplication of transposed matrices in reverse
R = E.T @ V.T @ I.T @ L.T

print(f"(LIVE)^T: \n{F}\n")
print(f"(E^T)(V^T)(I^T)(L^T): \n{R}\n")
print(f"Results are equal? {np.allclose(F,R)}")

(LIVE)^T: 
[[ 1.558  2.055  8.717]
 [ 0.085 -0.184  0.285]
 [-0.292  2.338  8.243]]

(E^T)(V^T)(I^T)(L^T): 
[[ 1.558  2.055  8.717]
 [ 0.085 -0.184  0.285]
 [-0.292  2.338  8.243]]

Results are equal? True
