In [1]:
import numpy as np

### Matrix Scalar Multiplication

#### 1. The Algebraic Rule

Scalar multiplication involves multiplying every individual element in a matrix $A$ by a single scalar value $\lambda$. If $A$ is an $m \times n$ matrix, then $\lambda A$ is also an $m \times n$ matrix where:

$$(\lambda A)_{i,j} = \lambda \cdot a_{i,j}$$

#### 2. Properties of Scalar Multiplication

Associativity: $(\alpha \beta)A = \alpha(\beta A)$

Distributivity over Matrix Addition: $\lambda(A + B) = \lambda A + \lambda B$

Distributivity over Scalar Addition: $(\lambda + \alpha)A = \lambda A + \alpha A$

#### 3. The Linearity Challenge

Question: Is matrix-scalar multiplication a Linear Operation?
Answer: Yes. For a transformation $T(A)$ to be linear, it must satisfy two properties:

Additivity: $T(A + B) = T(A) + T(B)$

$\lambda(A + B) = \lambda A + \lambda B$ (Verified by Distributivity)

Homogeneity: $T(\alpha A) = \alpha T(A)$

$\lambda(\alpha A) = \alpha(\lambda A)$ (Verified by Associativity)

#### 4. Technical Implementation (NumPy)

In Python, scalar multiplication is handled via broadcasting. NumPy automatically "stretches" the scalar across the entire dimensions of the matrix.

##### Standard implementation
result = lambda_val * A

#### 5. Engineering Reflection: Scaling and Normalization

In AI and Machine Learning, scalar multiplication is the primary tool for:

Feature Scaling: Adjusting the magnitude of input data.

Learning Rates: Scaling the gradient vector during backpropagation.

Stability: Much like the "Diagonal Shifting" done previously, scaling is used to prevent numerical overflow in deep neural networks.

In [20]:
# set global print options
np.set_printoptions(suppress=True, precision=3)

# create matrices
M = 5 # rows
N = 3 # columns

T = np.random.rand(M, N)
U = np.random.rand(M, N)
S = np.random.rand() #scalar

# scalar multiplication
resS = T * S
print(f"Random Matrix: \n{T}\n")
print(f"Scaled Matrix: \n{resS}\n")

# Code challenge: is scalar multiplication a linear operation?
# Testing Additivity: S * (T + U) == (S * T) + (S * U)
resL = S * np.add(T, U)
resR = np.add(S*T, S*U)
print(f"LHS (S * (T + U)): \n{resL}\n")
print(f"RHS (S*T + S*U): \n{resR}\n")

# Verify identity using np.allclose for floating point tolerance
is_linear = np.allclose(resL, resR)
print(f"Does LHS == RHS? {is_linear}")
print("Conclusion: The results are identical. Scalar multiplication is a linear operation.")


Random Matrix: 
[[0.538 0.702 0.874]
 [0.549 0.759 0.506]
 [0.623 0.71  0.128]
 [0.689 0.645 0.989]
 [0.905 0.053 0.69 ]]

Scaled Matrix: 
[[0.191 0.249 0.311]
 [0.195 0.27  0.18 ]
 [0.221 0.252 0.046]
 [0.245 0.229 0.351]
 [0.322 0.019 0.245]]

LHS (S * (T + U)): 
[[0.266 0.423 0.494]
 [0.243 0.361 0.247]
 [0.272 0.273 0.049]
 [0.495 0.249 0.644]
 [0.654 0.135 0.497]]

RHS (S*T + S*U): 
[[0.266 0.423 0.494]
 [0.243 0.361 0.247]
 [0.272 0.273 0.049]
 [0.495 0.249 0.644]
 [0.654 0.135 0.497]]

Does LHS == RHS? True
Conclusion: The results are identical. Scalar multiplication is a linear operation.
