In [1]:
# ======================================================================
# COMPLEXITY: O(m * n * p) - Dot product of each row A with each column B.
# DATA SHAPE: A(m, n) @ B(n, p) -> Result(m, p). Inner 'n' must match.
# MATH: Non-Commutative -> AB != BA. Associative -> (AB)C = A(BC).
# TOOLS: A @ B, np.matmul(A, B), A.dot(B)
# ======================================================================

import numpy as np

# set global print options
np.set_printoptions(suppress=True, precision=3)

### Standard Matrix Multiplication

The Rule: To multiply matrix $A$ by matrix $B$, the number of columns in $A$ must equal the number of rows in $B$.
* Shape Logic: $(m \times n) \times (n \times p) \rightarrow (m \times p)$
* The "Inner" Dimensions: Must match ($n$).
* The "Outer" Dimensions: Define the shape of the resulting matrix ($m \times p$).

🛠️ NumPy Implementation
Standard matrix multiplication (the Dot Product) is performed using @ or np.matmul() or A.dot(B).
* This is not the same as A * B (which is element-wise).

In [21]:
# create matrices

m = 2
n = 5
k = 7

A = np.random.randn(m,n) # 2x5 matrix
B = np.random.randn(n,k) # 5x7 matrix
C = np.random.randn(m,k) # 2x7 matrix

print(f"2x5 * 5x7 = 2x7 Matrix: \n{np.matmul(A,B)}\n")
print(f"5x2 * 2x7 = 5x7 Matrix: \n{A.T@C}\n")
print(f"5x7 * 7x5 = 5x5 Matrix: \n{B.dot(B.T)}\n")
print(f"7x5 * 5x7 = 7x7 Matrix: \n{(B.T@B)}\n")
print(f"2x7 * 7x5 = 2x5 Matrix: \n{(C@B.T)}\n")

2x5 * 5x7 = 2x7 Matrix: 
[[-1.799  1.572 -0.628 -1.856 -1.378 -0.677 -0.909]
 [ 1.193 -0.435 -0.985 -2.872 -2.497 -1.412  1.132]]

5x2 * 2x7 = 5x7 Matrix: 
[[-0.431 -0.607  0.221  0.692 -0.542 -0.196  0.765]
 [-0.21   1.7    0.844 -1.446 -0.459  0.426 -0.334]
 [-0.53  -0.888  0.219  0.976 -0.652 -0.278  0.99 ]
 [ 0.098  1.324  0.387 -1.216  0.007  0.354 -0.594]
 [-0.296  2.514  1.233 -2.143 -0.659  0.631 -0.513]]

5x7 * 7x5 = 5x5 Matrix: 
[[ 6.279  0.081  1.365  5.014 -1.739]
 [ 0.081  3.741 -1.345  1.581 -2.19 ]
 [ 1.365 -1.345 11.44   5.252  3.489]
 [ 5.014  1.581  5.252  8.867 -2.884]
 [-1.739 -2.19   3.489 -2.884  9.211]]

7x5 * 5x7 = 7x7 Matrix: 
[[12.095 -1.912 -2.757  0.893 -1.769 -6.206 -0.968]
 [-1.912  4.278  1.248  2.415  3.532 -0.6   -2.098]
 [-2.757  1.248  2.654  1.925  0.248  1.821 -0.851]
 [ 0.893  2.415  1.925  5.57   4.112 -0.119 -2.873]
 [-1.769  3.532  0.248  4.112  7.982  0.271 -1.324]
 [-6.206 -0.6    1.821 -0.119  0.271  4.325  1.014]
 [-0.968 -2.098 -0.851 -2.87

In [55]:
# ======================================================================
# SECTION: FOUR PERSPECTIVES OF MULTIPLICATION
# COMPLEXITY: O(m*n*p) - Logic varies, but total flop count is constant.
# DATA SHAPE: J(m, n), K(n, p) -> Result(m, p).
# MATH: Element (Dot), Column (Linear Combo), Row (Linear Combo), Layer (Outer).
# TOOLS: Slicing [row, col], np.outer()
# ======================================================================

# four ways to "think" about matrix multiplication
J = np.array( [(2, 4), (1, 2)] )
K = np.array( [(1, 2), (4, 7)] )

print(f"{J}\n \n{K}\n")
print(f"Standard Matrix Multiplication: \n{J@K}\n")

# element-wise perspective
E1 = (J[0, :] * K[:, 0]).sum()
E2 = (J[0, :] * K[:, 1]).sum()
E3 = (J[1, :] * K[:, 0]).sum()
E4 = (J[1, :] * K[:, 1]).sum()
E = np.array([(E1, E2), (E3, E4)])
print(f"Element-wise Perspective: \n{E}\n")

# layer perspective
L1 = np.outer(J[:,0], K[0, :] )
L2 = np.outer(J[:,1], K[1, :] )
print(f"Layer Perspective: \n{L1+L2}\n")

# column perspective
C1 = J[:, 0] * K[0, 0] + J[:, 1] * K[1, 0]
C2 = J[:, 0] * K[0, 1] + J[:, 1] * K[1, 1]
print(f"Column Perspective: \n{np.column_stack((C1,C2))}\n")

# row perspective
R1 = J[0, 0] * K[0, :] + J[0, 1] * K[1, :]
R2 = J[1, 0] * K[0, :] + J[1, 1] * K[1, :]
print(f"Row Perspective: \n{np.vstack((R1, R2))}")

[[2 4]
 [1 2]]
 
[[1 2]
 [4 7]]

Standard Matrix Multiplication: 
[[18 32]
 [ 9 16]]

Element-wise Perspective: 
[[18 32]
 [ 9 16]]

Layer Perspective: 
[[18 32]
 [ 9 16]]

Column Perspective: 
[[18 32]
 [ 9 16]]

Row Perspective: 
[[18 32]
 [ 9 16]]
