In [9]:
import numpy as np

### Transpose Operations and Complex Matrices

#### 1. Real Matrix TranspositionThe Operation:
Flipping a matrix over its diagonal ($M_{ij} \rightarrow M_{ji}$).

Implementation: Both np.transpose(M) and the .T attribute are used for standard arrays.

Verification: Dimensionality shifts from $(m \times n)$ to $(n \times m)$.

#### 2. Complex Matrices & The Hermitian Transpose (The Trap):
A standard transpose (.T) on complex numbers only flips the dimensions; it does not account for the phase of complex elements.

The Fix: For complex matrices, we use the Hermitian Transpose (or Conjugate Transpose).

Workflow: Use .conjugate().T to ensure the imaginary components are flipped ($a + bi \rightarrow a - bi$) alongside the positional flip.

#### 3. Environment & NumPy Best PracticesSuppress Scientific Notation:
* suppress=True to prevent small floats from cluttering the output.
* Precision: precision=3 for consistent numerical readability across Jupyter and Terminal.

In [11]:
# set global print options
np.set_printoptions(suppress=True, precision=3)

#create a matrix
M = np.array([[1,8,2],[4,9,3]])

print("\n" + "="*30, f"\nOriginal Matrix:\n{M}")

# you can transpose using np.transpose or .T if it's an array
print("\n" + ">"*30, f"\nTransposed Matrix Method 1:\n{M.T}\n")
print(f"Transposed Matrix Method 2:\n{np.transpose(M)}")
print(f"\n*Note: both methods complete the same operation.", "\n" + "<"*30, "\n")

# create a complex matrix
C = np.array([ [3+2j, 1, 6j] ])

print(f"Complex Matrix: \n{C}\n")
# when dealing with complex numbers, remember to use the Hermitian transpose
print(f"Complex Matrix Transposed (Using Hermitian Transpose):\n{C.conjugate().T}", "\n" + "="*30, "\n")



Original Matrix:
[[1 8 2]
 [4 9 3]]

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
Transposed Matrix Method 1:
[[1 4]
 [8 9]
 [2 3]]

Transposed Matrix Method 2:
[[1 4]
 [8 9]
 [2 3]]

*Note: both methods complete the same operation. 
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 

Complex Matrix: 
[[3.+2.j 1.+0.j 0.+6.j]]

Complex Matrix Transposed (Using Hermitian Transpose):
[[3.-2.j]
 [1.-0.j]
 [0.-6.j]] 

