In [1]:
import numpy as np

* This notebook covers the various "species" of matrices you will encounter in linear algebra. Understanding these definitions is critical for recognizing patterns in matrix operations and proofs.

1. Square vs. Rectangular

    The most basic classification based on dimensionality.

    * Square Matrix: A matrix with the same number of rows and columns ($M = N$).

        Property: Only square matrices have a defined main diagonal and a trace.

    * Rectangular Matrix: A matrix where $M \neq N$.

    * Tall Matrix: More rows than columns ($M > N$).

    * Wide Matrix: More columns than rows ($N > M$).

2. The Identity Matrix ($I$)

    A special square matrix that acts as the "1" of matrix multiplication.

    * Definition: 1s on the main diagonal, 0s everywhere else.

        Property: $AI = A$ and $IA = A$.

        Notation: Often written as $I_n$ to specify the size (e.g., $I_3$ is a $3 \times 3$ identity).

3. Diagonal Matrices

    * Definition: A square matrix where all elements off the main diagonal are zero ($d_{i,j} = 0$ for $i \neq j$).

        Significance: They are computationally efficient. Multiplying by a diagonal matrix simply scales the rows/columns.

4. Triangular Matrices

    * Upper-Triangular ($U$): All elements below the main diagonal are zero.

    * Lower-Triangular ($L$): All elements above the main diagonal are zero.

        Application: Crucial for LU Decomposition and solving systems of linear equations.

5. Symmetric vs. Skew-Symmetric

    These classifications relate to the matrix's relationship with its transpose ($A^T$).

    * Symmetric Matrix: $A = A^T$

        The matrix is a mirror image across its main diagonal.

            Example: Covariance matrices are always symmetric.

    * Skew-Symmetric (Anti-symmetric): $A^T = -A$

        Constraint: The main diagonal must be all zeros.

        Property: $a_{i,j} = -a_{j,i}$.

6. Zero (Null) Matrix

    * Definition: A matrix of any size where every element is 0.

        Notation: Often denoted simply as $0_{m,n}$.

7. Vector-like Matrices

    * Row Vector: A $1 \times N$ matrix.

    * Column Vector: An $M \times 1$ matrix.

        **Note: In modern data science and Mike's course, "vectors" are standardly treated as column vectors unless specified otherwise.

In [26]:
# set global print options
np.set_printoptions(suppress=True, precision=3)

# a square vs rectangular matrix
J = np.random.randn(4,4)
K = np.random.randn(4,2) # 4 rows, 2 columns
print(f"Square Matrix: \n{J}\n")
print(f"Rectangular Matrix: \n{K}\n")

# identity matrix
I = np.eye(6)
print(f"Identity Matrix: \n{I}\n")

# zero matrix
Z = np.zeros((5,5))
print(f"Zero Matrix: \n{Z}\n")

# diagonal matrix
D = np.diag([5, 2, 4])
print(f"Diagonal Matrix: \n{D}\n")

# Triangular Matrices
T = np.random.randn(4,4)
U = np.triu(T)
L = np.tril(T)
print(f"Upper Triangular Matrix: \n{U}\n")
print(f"Lower Triangular Matrix: \n{L}\n")

# concatenate matrices
C = np.random.randn(2, 2)
O = np.random.randn(2, 3)
N = np.concatenate((C, O), axis=1)
print(f"Concatenated Augmented Matrix: \n{N}")

Square Matrix: 
[[-1.482  1.086 -1.587 -1.673]
 [-0.532 -0.448  0.788  0.587]
 [-1.064 -0.523 -0.999  2.13 ]
 [ 0.827  0.379 -2.053  0.197]]

Rectangular Matrix: 
[[ 0.87  -0.925]
 [-1.749  0.974]
 [ 0.489  2.42 ]
 [ 0.61  -0.444]]

Identity Matrix: 
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Zero Matrix: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Diagonal Matrix: 
[[5 0 0]
 [0 2 0]
 [0 0 4]]

Upper Triangular Matrix: 
[[ 0.185  0.089  1.635 -0.036]
 [ 0.     0.401  0.963  0.254]
 [ 0.     0.     1.408 -0.312]
 [ 0.     0.     0.     0.409]]

Lower Triangular Matrix: 
[[ 0.185  0.     0.     0.   ]
 [-2.405  0.401  0.     0.   ]
 [ 0.766  0.117  1.408  0.   ]
 [ 0.02  -0.946  1.174  0.409]]

Concatenated Augmented Matrix: 
[[ 1.317 -0.454 -0.588 -0.645  0.296]
 [ 0.009  0.444  0.143  0.845 -0.978]]
